fixtures:
    symlinks:
      puppet-quagga: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      concat:
        repo: https://github.com/puppetlabs/puppetlabs-concat
      inifile:
        repo: https://github.com/puppetlabs/puppetlabs-inifile
    forge_modules:

