fixtures:
    symlinks:
      puppet-quagga: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.12.0
      concat:
        repo: https://github.com/puppetlabs/puppetlabs-concat
      inifile:
        repo: https://github.com/puppetlabs/puppetlabs-inifile
      logrotate:
        repo: https://github.com/yo61/puppet-logrotate
    forge_modules:

