fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "concat": "https://github.com/puppetlabs/puppetlabs-concat"
    "inifile": "https://github.com/puppetlabs/puppetlabs-inifile"
  symlinks:
    "quagga": "#{source_dir}"
